In [9]:
#Instalar libreria selium en colab
#!pip install selenium

#permitir el acceso a drive para guardar
#from google.colab import drive
#drive.mount('/content/drive')

# Importando bibliotecas

import pandas as pd

import numpy as np
from datetime import datetime
import matplotlib.pyplot as plt
import plotly.express as px
import yfinance as yf
from selenium import webdriver
from selenium.webdriver.common.by import By
import pandas as pd
import time

Requirement already satisfied: selenium in /usr/local/lib/python3.11/dist-packages (4.33.0)
Requirement already satisfied: urllib3~=2.4.0 in /usr/local/lib/python3.11/dist-packages (from urllib3[socks]~=2.4.0->selenium) (2.4.0)
Requirement already satisfied: trio~=0.30.0 in /usr/local/lib/python3.11/dist-packages (from selenium) (0.30.0)
Requirement already satisfied: trio-websocket~=0.12.2 in /usr/local/lib/python3.11/dist-packages (from selenium) (0.12.2)
Requirement already satisfied: certifi>=2025.4.26 in /usr/local/lib/python3.11/dist-packages (from selenium) (2025.6.15)
Requirement already satisfied: typing_extensions~=4.13.2 in /usr/local/lib/python3.11/dist-packages (from selenium) (4.13.2)
Requirement already satisfied: websocket-client~=1.8.0 in /usr/local/lib/python3.11/dist-packages (from selenium) (1.8.0)
Requirement already satisfied: attrs>=23.2.0 in /usr/local/lib/python3.11/dist-packages (from trio~=0.30.0->selenium) (25.3.0)
Requirement already satisfied: sortedcontainers in /usr/local/lib/python3.11/dist-packages (from trio~=0.30.0->selenium) (2.4.0)
Requirement already satisfied: idna in /usr/local/lib/python3.11/dist-packages (from trio~=0.30.0->selenium) (3.10)
Requirement already satisfied: outcome in /usr/local/lib/python3.11/dist-packages (from trio~=0.30.0->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in /usr/local/lib/python3.11/dist-packages (from trio~=0.30.0->selenium) (1.3.1)
Requirement already satisfied: wsproto>=0.14 in /usr/local/lib/python3.11/dist-packages (from trio-websocket~=0.12.2->selenium) (1.2.0)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in /usr/local/lib/python3.11/dist-packages (from urllib3[socks]~=2.4.0->selenium) (1.7.1)
Requirement already satisfied: h11<1,>=0.9.0 in /usr/local/lib/python3.11/dist-packages (from wsproto>=0.14->trio-websocket~=0.12.2->selenium) (0.16.0)
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [10]:

url = 'https://hedgefollow.com/funds/Berkshire+Hathaway'

options = webdriver.FirefoxOptions()
# options.headless = True
options.add_argument('-headless')


driver = webdriver.Firefox(options=options)
driver.get(url)

time.sleep(3)

table = driver.find_element(By.ID, 'fund_holdings_equities')

headers = []
rows = []
#print('--- headers ---')
header_row = table.find_elements(By.TAG_NAME, 'tr')[0]
for cell in header_row.find_elements(By.TAG_NAME, 'th'):
    if(cell.get_attribute("style").find("display: none")<0):
      headers.append(cell.text)

# print(headers)

# print('--- data ---')
data_rows = table.find_elements(By.TAG_NAME, 'tr')[1:]
for row in data_rows:
    row_data = {}
    children = row.find_elements(By.TAG_NAME, 'td')
    if(len(children) > 1):
      for i, cell in enumerate(children):
          row_data[headers[i]] = cell.text
      rows.append(row_data)

driver.quit()

df_bh = pd.DataFrame(rows)


df_bh.head()

,Stock,Company Name,% of Portfolio,Shares Owned,Value Owned,Latest Activity,Ownership Hist,Average Buy Price,Price History,Date
0,AAPL,Apple Inc,25.76%,300,$ 66.64,0%,,$39.59 (+407.7%),,2025-03-31
1,AXP,American Express Co,15.77%,151.61,$ 40.79,0%,,$71.11 (+319.9%),,2025-03-31
2,KO,Coca Cola Co,11.07%,400,$ 28.65,0%,,$40.28 (+70.9%),,2025-03-31
3,BAC,Bank America Corp,10.19%,631.57,$ 26.36,-7.15% (-48.66\n),,$25.78 (+76.5%),,2025-03-31
4,CVX,Chevron Corp New,7.67%,118.61,$ 19.84,0%,,$132.76 (+12.6%),,2025-03-31

In [11]:
df_bh.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Stock              38 non-null     object
 1   Company Name       38 non-null     object
 2   % of Portfolio     38 non-null     object
 3   Shares Owned       38 non-null     object
 4   Value Owned        38 non-null     object
 5   Latest Activity    38 non-null     object
 6   Ownership Hist     38 non-null     object
 7   Average Buy Price  38 non-null     object
 8   Price History      38 non-null     object
 9   Date               38 non-null     object
dtypes: object(10)
memory usage: 3.1+ KB

In [12]:
# Eliminando las columnas innecesarias
df_bh = df_bh.drop(['Ownership Hist', 'Average Buy Price', 'Price History'], axis=1)

In [13]:
df_bh.head()

,Stock,Company Name,% of Portfolio,Shares Owned,Value Owned,Latest Activity,Date
0,AAPL,Apple Inc,25.76%,300,$ 66.64,0%,2025-03-31
1,AXP,American Express Co,15.77%,151.61,$ 40.79,0%,2025-03-31
2,KO,Coca Cola Co,11.07%,400,$ 28.65,0%,2025-03-31
3,BAC,Bank America Corp,10.19%,631.57,$ 26.36,-7.15% (-48.66\n),2025-03-31
4,CVX,Chevron Corp New,7.67%,118.61,$ 19.84,0%,2025-03-31

In [16]:
# Guardando el DataFrame en un archivo CSV (Local)
df_bh.to_csv('./data/berkshire_porfolio.csv', index=False)

# Guardando el DataFrame en un archivo CSV /(En drive)
#df_bh.to_csv('/content/drive/MyDrive/berkshire_porfolio.csv', index=False)